"""
Schedule model for storing daily schedule options.
"""
from datetime import datetime
from app.extensions import db

class Schedule(db.Model):
    """Daily schedule generated by Lambda agent."""
    __tablename__ = 'schedules'
    
    id = db.Column(db.Integer, primary_key=True)
    generated_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    task_count = db.Column(db.Integer, nullable=False)
    research_data = db.Column(db.Text)  # JSON string of research findings
    schedules_data = db.Column(db.Text, nullable=False)  # JSON string of all 3 schedule options
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    def to_dict(self):
        """Convert schedule to dictionary."""
        import json
        return {
            'id': self.id,
            'date': self.generated_date.isoformat(),
            'task_count': self.task_count,
            'research': json.loads(self.research_data) if self.research_data else [],
            'schedules': json.loads(self.schedules_data),
            'created_at': self.created_at.isoformat()
        }
